config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'admins'      => 'users#adminlist'
  get    'createuseradmin'      => 'users#new'
  get '/roomhistory/:id', to: 'histories#roomhistory',  via: :get, as: :room_history
  
  resources :users
  get  '/users/:id(.:format)/upgrade' => 'users#upgrade'
  get  '/users/:id(.:format)/downgrade' => 'users#downgrade'

  resources :rooms
  get   'update'  => 'rooms#update'
 
  resources :histories
  get   'search'  => 'histories#search'
  
end

app/models/history.rb
class History < ApplicationRecord
    validates :room_id, presence: true, length: { maximum: 50 }
    validates :user_email, presence: true, length: { maximum: 50 }
    validates :startTime, presence: true
    validates :endTime, presence: true
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :admin_user, only: [:index, :show]
  def index
    @histories = History.paginate(page: params[:page])
  end

  def new
    @history = History.new
  end

  def create
    @history = History.new(history_params)    # not finised
    @history.startTime = @history.startTime.to_time + 0.minutes
    @history.endTime = @history.endTime.to_time + 0.minutes
    # need some constraints here. only one booking per day.... , if xbm@qq.com is in user list

    if !Room.exists?(room_id: @history.room_id)
      flash[:danger] = "Room not exists"
      render 'new' and return
    end
    if !User.exists?(email: @history.user_email)
      flash[:danger] = "User not exists"
      render 'new' and return
    end
    if @history.startTime.to_time > Time.now+7.days
      flash[:danger] = "booking up to 7 days ahead"
      render 'new' and return 
    end
    if @history.endTime.to_time <= Time.now - 3.hours
      flash[:danger] = "time selected has past"
      render 'new' and return 
    end
    
    #check availability
    @hists = History.where(room_id: @history.room_id)

    @hists.each do |h|
      if h.startTime<=@history.startTime and h.endTime>@history.startTime
        flash[:danger] = "Conflict"
        render 'new' and return
      end
      if h.startTime<@history.endTime and h.endTime>=@history.endTime
        flash[:danger] = "Conflict"
        render 'new' and return 
      end
    end
    if !current_user.admin?
      temp = History.where(user_email: @history.user_email)
      temp.each do |t|
        if t.startTime.to_time.to_date==@history.startTime.to_time.to_date
          flash[:danger] = "member cannot book 2 room within a day, please cancel your previous booking to proceed "
          render 'new' and return
        end
      end
    end
    
    if @history.save
      UserNotifierMailer.send_reserve_email(current_user.email, @history, params[:history][:building]).deliver
      flash[:success] = "The history has been created"
      if current_user.admin? 
        redirect_to histories_url
      else 
        redirect_to current_user
      end
    else
      flash[:danger] = "not created"
      render 'new'
    end
  end

  def show
     @history = History.find(params[:id])
  end
  
  def destroy
    History.find(params[:id]).destroy
    flash[:success] = "History deleted"
    redirect_to current_user
  end
  
  def search
    @rooms = []
    if params.has_key?(:start_time)
      @size = params[:size]
      @building = params[:building]
      @search_start_time = DateTime.new(params[:start_time]['year'].to_i ,params[:start_time]['month'].to_i ,params[:start_time]['day'].to_i ,params[:start_time]['hour'].to_i ,00,00)
      @search_end_time = @search_start_time + 2.hours
      if @search_end_time <= Time.now - 3.hours
        flash[:danger] = "time selected has past, select a new time"
      end
=begin
      if @search_start_time > Time.now+7.days
        flash[:danger] = "booking up to 7 days ahead"
      end
=end
=begin
      subquery = Room.joins("LEFT OUTER JOIN histories on rooms.room_id = histories.room_id").where("((? >= histories.startTime AND ? < histories.endTime ) OR ( ? > histories.startTime AND ? <= histories.endTime ))", @search_start_time, @search_start_time, @search_end_time, @search_end_time).distinct.select('rooms.room_id')
=end
      subquery = []
      History.all.each do |h|
        if h.startTime<=@search_start_time and h.endTime>@search_start_time
          subquery.push(h.room_id)
        end
        if h.startTime<@search_end_time and h.endTime>=@search_end_time
          subquery.push(h.room_id)
        end
      end
      if subquery==[]
        @rooms = Room.all
      elsif @size != 'Any' and @building != 'Any'
        @rooms = Room.where(" room_id not in (?)", subquery).where(" size = ?", @size).where(" building = ?", @building)
      elsif @size != 'Any'
        @rooms = Room.where(" room_id not in (?)", subquery).where(" size = ?", @size)
      elsif @building != 'Any'
        @rooms = Room.where(" room_id not in (?)", subquery).where(" building = ?", @building)
      else
        @rooms = Room.where(" room_id not in (?)", subquery)
      end
      #@rooms = Room.where("room_id in (?)", subquery)
      #@rooms = Room.all
      #@rooms = subquery
    end
  end
  
  def roomhistory
    @room = Room.find(params[:id])
    @histories = History.where(room_id: @room.room_id).order(:startTime)
  end
  
  private
    def history_params
      params.require(:history).permit(:user_email, :room_id, :startTime, :endTime)
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    def pre_admin_user
      redirect_to(root_url) unless current_user.admin? and current_user.pre_admin?
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>

<% if params and params.key?('start_time') %>
  <div class="field">
    <%= f.label :startTime %>
    <%= f.hidden_field :startTime, :value => DateTime.parse(params['start_time']) %>
    <%= DateTime.parse(params['start_time']).strftime("%Y-%b-%d %I%p") %>
  </div>
<% end %>
<% if params and params.key?('end_time') %>
  <div class="field">
    <%= f.label :endTime %>
    <%= f.hidden_field :endTime, :value => DateTime.parse(params['end_time']) %>
    <%= DateTime.parse(params['end_time']).strftime("%Y-%b-%d %I%p") %>
  </div>
<% end %>
  <div class="field">
    <%= f.label :room_id %>
    <%= f.hidden_field :room_id, :value => params['room'] %>
    <%= params['room'] %>
  </div>
    <div class="field">
    <%= f.label :size %>
    <%= f.hidden_field :size, :value => params['size'] %>
    <%= params['size'] %>
  </div>
    <div class="field">
    <%= f.label :building %>
    <%= f.hidden_field :building, :value => params['building'] %>
    <%= params['building'] %>
  </div>
  <div class="field">
  <% if current_user.admin? %>
    <%= f.label :user_email %>
    <%= f.text_field :user_email, class: 'form_control' %> 
  <% else %>
    <%= f.label :user_email %>
    <%= f.hidden_field :user_email, :value => current_user.email %>
    <%= current_user.email %>
  <% end %>
  </div>

  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/histories/_history.html.erb
<li>
  <%= link_to history.id, history %>
    |<%= history.room_id %>
    |<%= history.user_email %>
    |<%= history.startTime.to_time.strftime("%Y-%b-%d %I%p") %>
    -<%= history.endTime.to_time.strftime("%Y-%b-%d %I%p") %>
    
    
    <% if current_user.pre_admin? %>
    | <%= link_to "delete", history, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>

</li>

app/views/histories/create.html.erb
<h1>Histories#create</h1>
<p>Find me in app/views/histories/create.html.erb</p>

app/views/histories/index.html.erb
<% provide(:title, 'All histories') %>
<h1>All histories</h1>

<%= will_paginate %>

<ul class="histories">
  <%= render @histories %>
</ul>

<% if isadmin? %>
    <%= link_to "New booking histories", search_path, class: "btn btn-lg btn-primary" %>
<% end %>

<%= will_paginate %>

app/views/histories/new.html.erb
<% provide(:title, 'New Booking') %>
<% provide(:button_text, 'Create New Booking') %>
<h1>Create new booking</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/histories/roomhistory.html.erb
<p id="notice"><%= notice %></p>
<h1><%= "Room #{@room.room_id} booking histories:" %></h1>
      <% current, past = [], [] %>
      <% for h in @histories %>
        <% if h.endTime<Time.now-3.hours %>
          <% past.push(h) %>
        <% else %>
          <% current.push(h) %>
        <% end %>
      <% end %>
      <br><strong>Current booking</strong><br><br>
      <% for h in current %>
      <li>
        <%= h.user_email %> | <%= h.startTime.to_time.strftime("%Y-%b-%d %I%p") %> - <%= h.endTime.to_time.strftime("%Y-%b-%d %I%p") %> | <%= link_to "Cancel Booking", h, method: :delete,
                                  data: { confirm: "You sure?" } %>
      </li>
      <% end %>
      <br><strong>Past booking</strong><br><br>
      <% for h in past %>
      <li>
        <%= h.user_email %> | <%= h.startTime.to_time.strftime("%Y-%b-%d %I%p") %> - <%= h.endTime.to_time.strftime("%Y-%b-%d %I%p") %> 
      </li>
      <% end %>
      

app/views/histories/search.html.erb
<h1> Search for available rooms</h1>

<%= form_tag(search_path, :method => "get", id: "search-form") do %>
  <div class="field">
      <%= label_tag :"start time" %>
      <%= select_datetime(Time.now - 3.hours, :discard_minute => true, :prefix => :start_time) %>
  </div>
  
  <div>
      <%= label_tag :"Size" %><br>
      Small (4 seats)
      <%= radio_button_tag :size, 'Small' %> Medium (6 seats)
      <%= radio_button_tag :size, 'Medium' %> Large (12 seats)
      <%= radio_button_tag :size, 'Large' %> Any
      <%= radio_button_tag :size, 'Any', true %>
  </div>
  
  <div>
    <%= label_tag :"Building" %><br>
    D.H.Hill
    <%= radio_button_tag :building, 'D.H.Hill' %> James.B.Hunt
    <%= radio_button_tag :building, 'James.B.Hunt' %> Any
    <%= radio_button_tag :building, 'Any', true %>
  </div>

  <%= submit_tag "Check availability and Book" , class: "btn btn-primary"%>
<% end %>


<p id="notice"><%= notice %></p>
<%if not defined?(@rooms) or @rooms.empty? %>
    <p>There are no rooms.</p>
<%else%>
<h1>Rooms</h1>

<table>
  <thead>
  <tr>
    <th>Room number</th>
    <th>Size</th>
    <th>Building</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_id %></td>
        <td><%= room.size %></td>
        <td><%= room.building %></td>
        <td><%= link_to 'Book',new_history_path(:room => room.room_id, :start_time => @search_start_time, :end_time => @search_end_time, :size => room.size, :building => room.building) %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>
<br>

app/views/histories/show.html.erb
<p>
  <strong>Start Time:</strong>
  <%= @history.startTime.to_time.strftime("%Y-%b-%d %I%p") %>
</p>

<p>
  <strong>End Time:</strong>
  <%= @history.endTime.to_time.strftime("%Y-%b-%d %I%p") %>
</p>

<p>
  <strong>Room:</strong>
  <%= @history.room_id %>
</p>

<p>
  <strong>Library member:</strong>
  <%= @history.user_email %>
</p>