config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'admins'      => 'users#adminlist'
  get    'createuseradmin'      => 'users#new'
  get '/roomhistory/:id', to: 'histories#roomhistory',  via: :get, as: :room_history
  
  resources :users
  get  '/users/:id(.:format)/upgrade' => 'users#upgrade'
  get  '/users/:id(.:format)/downgrade' => 'users#downgrade'

  resources :rooms
  get   'update'  => 'rooms#update'
 
  resources :histories
  get   'search'  => 'histories#search'
  
end

app/models/room.rb
class Room < ApplicationRecord
    validates :room_id, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50 }
    #validates :build, presence: true, length: { maximum: 50 }
    validates :size, presence: true
    validates :building, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy, :edit, :update]
  before_action :admin_user,     only: [:new, :create, :destroy]
  def index
    @rooms = Room.paginate(page: params[:page])
  end
  
  def show
    @room = Room.find(params[:id])
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)    # not finised
    if @room.save
      flash[:success] = "The room has been created"
      redirect_to @room
    else
      render 'new'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    his = History.where(room_id: @room.room_id)
      flag = false
      for i in his
        if i.endTime>=Time.now-3.hours
          flag = true
          break
        end
      end
      if flag
        flash[:danger] = "This room has pending reservations, please cancel the booking before delete the room"
        redirect_to rooms_url and return 
      end
    @room.destroy
    flash[:success] = "Room deleted"
    redirect_to rooms_url
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find_by(room_id: params[:rid])
    @history = History.new
    @history.user_email = current_user.email
    @history.room_id = params[:rid]
    @history.startTime = params[:start_time][0].to_time
    @history.endTime = params[:start_time][0].to_time + 2.hours
    if @history.startTime > Time.now+7.days
      flash[:danger] = "booking up to 7 days ahead"
      redirect_to @room and return
    end
    
    @hists = History.where(room_id: @history.room_id)
    @hists.each do |h|
        if h.startTime<@history.startTime and h.endTime>@history.startTime
          flash[:danger] = "Conflict"
          redirect_to @room and return
        end
        if h.startTime>@history.startTime and h.startTime<@history.endTime
          flash[:danger] = "Conflict"
          redirect_to @room and return
        end
    end
    
    if @history.save
      flash[:success] = "The room has been booked"
      redirect_to @room
    else
      flash[:danger] = "Something wrong: the room not booked successfully"
      redirect_to @room
    end

=begin
    @room = Room.find_by_id(params[:id])
    if @room.update_attributes(room_params)
      if @room.status==true
          flash[:success] = "have booked"
          redirect_to @room
      else
          flash[:success] = "not booked "
          redirect_to @room
      end
    else
      render 'edit'
    end
=end
  end
  

  
  private
    def room_params
      params.require(:room).permit(:room_id, :size, :building)
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>

  <%= f.label :room_id %>
  <%= f.text_field :room_id, class: 'form-control' %>

  <%= f.label :size %>
  <%= f.select :size, [['Small - 4 chairs','Small'],['Medium - 6 chairs','Medium'],['Large - 12 chairs','Large']], class: 'form-control' %>
  
  <%= f.label :building %>
  <%= f.select :building, [['D.H.Hill','D.H.hill'],['James.B.Hunt','James.B.Hunt']], class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/rooms/_room.html.erb
<li>
  <%= link_to room.room_id, room %>
    |   <%= room.size %>    |   <%= room.building %>    |   
    <%= link_to "Book", room %>
    <% if current_user.admin? %>
    | <%= link_to "delete", room, method: :delete,
                                  data: { confirm: "You sure?" } %>
    | <%= link_to "view room history", room_history_path(room) %>
    <% end %>

</li>

app/views/rooms/edit.html.erb
<% provide(:title, "Book room") %>
<h1>Book room</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@room) do |f| %>
    <%= f.radio_button :status, "false" , checked: true %>
    <%= f.label :status, "THINK AGAIN", :value => "false" %></p>
    <%= f.radio_button :status ,"true" %>
    <%= f.label :status, "I WANT TO BOOK", :value => "true"  %></p>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  
  </div>
</div>

app/views/rooms/index.html.erb
<% provide(:title, 'All rooms') %>
<h1>All rooms</h1>

<%= will_paginate %>

<ul class="rooms">
  <%= render @rooms %>
</ul>

<%= link_to "Search for available rooms", search_path, class: "btn btn-lg btn-primary" %>

<% if isadmin? %>
    <%= link_to "Create A Room", new_room_path, class: "btn btn-lg btn-primary" %>
<% end %>



<%= will_paginate %>

app/views/rooms/new.html.erb
<% provide(:title, 'Create new room') %>
<% provide(:button_text, 'Create') %>
<h1>Create new room</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/rooms/show.html.erb
<% provide(:title, @room.room_id) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @room.room_id %>
      </h1>
      <h2>Size: <%= @room.size %></h2>
      <p>Available time:</p><br>
      <p>Book this room within 7 days from now, enter the start time you want to book this room. </p>
      
      <%= form_tag(update_path, :method => "get", id: "update-form") do %>
            <%= datetime_local_field :start_time, params[:start_time], placeholder: "Start Time",  class: 'form-control' %>
            <%= hidden_field_tag "rid", @room.room_id%>
            <%= submit_tag "Check availability and Book" , class: "btn btn-primary"%>
      <% end %>
      
      <p>Room may not be available if it has been book within the time you select. </p>
    </section>
  </aside>
</div>